### PR TITLE
135 `calc_*` functions should output NAs is there is no available data

### PR DESCRIPTION
**Pull request by CeresBarros**
https://github.com/bcgov/climr/issues/135

Tests for `calc_*` functions could evolve into comparing with data from ClimateBC. This is a start, though.

To be continued...

### CODE REVIEW

**Comment by CeresBarros** [comment]
partially addresses t #133

**Review by kdaust — APPROVED** [review]

**Comment by CeresBarros** [comment]
@kdaust it seems check are failing because the server can't be reached. Any clues as to what might be happening?

**Comment by kdaust** [comment]
Should be fixed now - not sure why but postgres quit. Has been happening if someone uses the old climRdev and requests a large area.

**Comment by CeresBarros** [comment]
@kdaust the checks keep failing due to server issues. Can you check the failing test code and see if I'm doing anything wrong that could be triggering server issues?

**Comment by kdaust** [comment]
Do you know which tests are causing the fail? Is it the calc_* function test? Also, would it make sense to focus on the main climr_downscale function, instead of using the underlying functions directly? Although I suppose it doesn't matter for testing the calculations

**Comment by kdaust** [comment]
I tried running the test and it ran fine - I wonder if the problem is being caused by multiple instances trying to pull from the database at the same time? You're downloading the entire prism surface of BC, so that's fairly large. Maybe try using a much smaller bounding box for the tests and see if that works?

**Comment by CeresBarros** [comment]
It is the second test that fails. As to the size of the bbox, I was using what was available in `Example_Run.R`. If you have a smaller example, do send it along ;)

**Pull request merged**
