### PR TITLE
Bug fix in plot_bivariate

### PR DESCRIPTION
**Pull request by cmahony**
one-line bug fix, with bump and NEWS and redoc.

### CODE REVIEW

**Comment by CeresBarros** [comment]
All vignette builds are now failing with some sort of `data.frame` algebra error. This should be investigated before merging, even if not related to your bugfix.

@kdaust Have you seen this during your own checks?

**Comment by cmahony** [comment]
I'm getting these fails as well in my own runs on devl.

**Comment by kdaust** [comment]
Sorry this is all my fault. I'll try and fix tonight

**Comment by cmahony** [comment]
> Sorry this is all my fault. I'll try and fix tonight

@kdaust no problems! it can wait until later this week if you have other things on the go.

**Comment by kdaust** [comment]
I *think* it's fixed. Tests are running now

**Comment by CeresBarros** [comment]
I merged @kdaust 's fixes and relaunched tests

**Comment by kdaust** [comment]
I think the tests will still fail due to the out$GCM error. It's also failing locally, but I haven't been able to pinpoint the bug yet

**Comment by kdaust** [comment]
All tests passing except for the one due to incorrect comparison data. Merged

**Comment by CeresBarros** [comment]
Reminder: please rebuild the testing datasets on the new `main` branch version, push and re run tests (maybe locally?) to make sure all is passing
On 10 Apr 2024, at 17:36, Kiri Daust ***@***.******@***.***>> wrote:

All tests passing except for the one due to incorrect comparison data. Merged

**Pull request merged**
